layout_spectrum: 0.04457569
color:
  saturation: 0.5429646
  brandStrength: 0.6376951
  lightness: 0.3754028
  rhythmicContrast: 0.4226638
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
typography_spectrum: 0.9038668
name: 'The Ground Floor Entrepreneur '
